# change the followings to match your Github username and repo name
baseurl: "/lekas" # the name of your github repo
url: "https://bagelcow.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "LEKS.GG"
description: welcome:)

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Leks
author-bio: 25 | ğŸ‡µğŸ‡¹ | ğš¿  # change to false to hide
author-image: coolcat.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Dama Archive
  permalink: archive
# - text: Blog
#  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "LEKS.GG"
footer-msg-link: #

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
