# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://leks.gg" # the url of your github pages

# site information used in page title, meta data etc.
title: "LEKS.GG"
description: welcome:)

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Hi, I am Leks
author-bio: I'm 25. I love the human mind ğŸ§ , tech stuff ğŸ’», music â™« and everything space ğŸŒŒ. I am currently studying Psychology ğš¿. I have worked on multiple projects, from hosting game servers and discord bots to some web development. I am always eager to work on new things that catch my interest! If I managed to captivate yours, feel free to reach out.  # change to false to hide
author-image: coolcat.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
# - text: Dama Archive
#   permalink: archive
- text: Playlist Suggestion
  permalink: playlists

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false
discord: false

# footer information
footer-msg: "LEKS.GG"
footer-msg-link: #

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
